'use client';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { demoUsers, demoPassword } from '../../lib/demo-users';
export default function Login() {
  const router = useRouter();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState('');
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const user = demoUsers.find(user => user.email === email.trim().toLowerCase()); if (!user || password !== demoPassword) { setError('Use an example user below and the demo password shown on this page.'); return; } router.push(`/preview?role=${user.id}`); }
  return <section className="login-layout"><aside className="login-story"><p className="eyebrow">Your next chapter starts here</p><h1>Good things happen<br/>when you <em>show up.</em></h1><div className="login-art" aria-hidden="true"><span>✳</span><span>◒</span><span>≈</span></div><p>New ideas. Fresh perspectives.<br/>People who believe in your creative voice.</p><span className="small-label">WRITING &nbsp; / &nbsp; VISUAL ART &nbsp; / &nbsp; MUSIC</span></aside><div className="login-panel"><p className="eyebrow">Welcome to Xpression</p><h2>A space of your own.</h2><p className="muted">Log in to preview your creative community.</p><div className="notice">Design prototype · Fictional accounts only. No real authentication or data storage.</div><form onSubmit={submit}><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="off" placeholder="you@example.com" required value={email} onChange={event => { setEmail(event.target.value); setError(''); }}/><label htmlFor="password">Password</label><div className="password-field"><input id="password" type={showPassword ? 'text' : 'password'} autoComplete="off" required value={password} onChange={event => setPassword(event.target.value)}/><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? 'Hide' : 'Show'}</button></div>{error && <p role="alert" className="error">{error}</p>}<button className="button primary full-width" type="submit">Preview my space <span aria-hidden="true">↗</span></button></form><div className="demo-heading"><h3>Meet the example users</h3><p>Select a user to fill in the form. Shared demo password: <code>{demoPassword}</code></p></div><div className="demo-users">{demoUsers.map(user => <button type="button" className="demo-user" key={user.id} onClick={() => { setEmail(user.email); setPassword(demoPassword); setError(''); }}><span className={`avatar ${user.id}`}>{user.initials}</span><span><strong>{user.name}</strong><small>{user.role}</small><small>{user.email}</small></span><span className="user-arrow" aria-hidden="true">↗</span></button>)}</div></div></section>;
}
